process.env =  { MANPATH: '/Users/will/.nvm/v0.8.22/share/man:',
  TERM_PROGRAM: 'iTerm.app',
  TERM: 'xterm-256color',
  SHELL: '/bin/bash',
  CLICOLOR: '1',
  TMPDIR: '/var/folders/7x/pp90vq196z7ch59qfps3j1hc0000gn/T/',
  NVM_PATH: '/Users/will/.nvm/v0.8.22/lib/node',
  Apple_PubSub_Socket_Render: '/tmp/launch-2dHlU0/Render',
  NVM_DIR: '/Users/will/.nvm',
  USER: 'will',
  COMMAND_MODE: 'unix2003',
  SSH_AUTH_SOCK: '/tmp/launch-caZggA/Listeners',
  __CF_USER_TEXT_ENCODING: '0x1F5:25:52',
  Apple_Ubiquity_Message: '/tmp/launch-8BXR8h/Apple_Ubiquity_Message',
  LSCOLORS: 'gxfxcxdxbxegedabagacad',
  PATH: '/Users/will/.nvm/v0.8.22/bin:/Users/will/Library/Bin:/usr/local/mysql/bin:/usr/local/redis-2.6.14/src:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/X11/bin',
  PWD: '/Users/will/Exercise/Nodejs/ProcessTest',
  LANG: 'zh_CN.UTF-8',
  ITERM_PROFILE: 'Default',
  PS1: '\\u@mac:\\w $ ',
  SHLVL: '1',
  HOME: '/Users/will',
  ITERM_SESSION_ID: 'w0t8p1',
  LOGNAME: 'will',
  PREFIX: '/Users/will/.nvm/v0.8.22',
  NVM_BIN: '/Users/will/.nvm/v0.8.22/bin',
  DISPLAY: '/tmp/launch-uIjKYt/org.macosforge.xquartz:0',
  SECURITYSESSIONID: '186a4',
  _: '/Users/will/.nvm/v0.8.22/bin/node' } 

