/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_marakana_jniexamples_InstanceAccess */

#ifndef _Included_com_marakana_jniexamples_InstanceAccess
#define _Included_com_marakana_jniexamples_InstanceAccess
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_marakana_jniexamples_InstanceAccess
 * Method:    propertyAccess
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_marakana_jniexamples_InstanceAccess_propertyAccess
  (JNIEnv *, jobject);

/*
 * Class:     com_marakana_jniexamples_InstanceAccess
 * Method:    methodAccess
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_marakana_jniexamples_InstanceAccess_methodAccess
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
