######################################################################
# Automatically generated by qmake (3.0) Sun Jul 31 10:27:28 2016
######################################################################

TEMPLATE = app
TARGET = foo
INCLUDEPATH += .
QT += widgets

# Input
SOURCES += foo.cpp
