apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: redis-ns
  labels:
    app: redis-service
spec:
  type: ClusterIP
  ports:
  - name: redis-port
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: redis-service

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  namespace: redis-ns
  labels:
    app: redis
spec:
  replicas: 1
  template:
    metadata:
     labels:
       name: redis
    spec:
      containers:
      - name: redis
        image: redis:6.2.1-alpine3.13
        volumeMounts:
        - name: redis-conf
          mountPath: /etc/redis
        command:
          - redis-server
        args:
          - "/etc/redis/redis.conf"
      volumes:
      - name: redis-conf
        configMap:
          name: redis-conf
          items:
            - key: redis.conf
              path: redis.conf

