# 使用官方提供的Node.js开发镜像作为基础镜像
FROM node:10.14.2-alpine

# 创建工作目录 /root/workspace
RUN mkdir -p /root/workspace

# 将工作目录切换为 /root/workspace
WORKDIR /root/workspace

# 将当前目录下的所有内容复制到 /root/workspace 下
ADD . /root/workspace

# 设置容器进程为: node cli.js, 即: 这个Node.js应用的启动命令
ENTRYPOINT ["node", "cli.js"]

