######################################################################
# Automatically generated by qmake (2.01a) ?? 4? 27 14:59:19 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
