apiVersion: v1
kind: Service
metadata:
  name: redis-cluster-service-a
  namespace: redis-cluster-ns
  labels:
    app: redis-cluster-service-a
spec:
  ports:
  - name: redis-port
    port: 6379
  clusterIP: None
  selector:
    app: redis-stateful-set-a
    appCluster: redis-cluster-a

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-stateful-set-a
  namespace: redis-cluster-ns
spec:
  serviceName: redis-cluster-service-a
  replicas: 1
  selector:
    matchLabels:
      app: redis-stateful-set-a
  template:
    metadata:
      labels:
        app: redis-stateful-set-a
        appCluster: redis-cluster-a
    spec:
      terminationGracePeriodSeconds: 20
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - redis
              topologyKey: kubernetes.io/hostname
      containers:
      - name: redis
        image: redis:v6.0.8
        command:
          - redis-server
        args:
          - "/etc/redis/redis.conf"
          - "--protected-mode"
          - "no"
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
            - name: redis
              containerPort: 6379
              protocol: TCP
            - name: cluster
              containerPort: 16379
              protocol: TCP
        volumeMounts:
          - name: redis-conf
            mountPath: /etc/redis
      volumes:
      - name: redis-conf
        configMap:
          name: redis-conf
          items:
            - key: redis.conf
              path: redis.conf

---

apiVersion: v1
kind: Service
metadata:
  name: redis-access-service-a
  namespace: redis-cluster-ns
  labels:
    app: redis-access-service-a
spec:
  type: ClusterIP
  ports:
  - name: tcp-port
    protocol: TCP
    port: 6379
    targetPort: 6379
  selector:
    app: redis-stateful-set-a
    appCluster: redis-cluster-a

---
---

apiVersion: v1
kind: Service
metadata:
  name: redis-cluster-service-b
  namespace: redis-cluster-ns
  labels:
    app: redis-cluster-service-b
spec:
  ports:
  - name: redis-port
    port: 6379
  clusterIP: None
  selector:
    app: redis-stateful-set-b
    appCluster: redis-cluster-b

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-stateful-set-b
  namespace: redis-cluster-ns
spec:
  serviceName: redis-cluster-service-b
  replicas: 1
  selector:
    matchLabels:
      app: redis-stateful-set-b
  template:
    metadata:
      labels:
        app: redis-stateful-set-b
        appCluster: redis-cluster-b
    spec:
      terminationGracePeriodSeconds: 20
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - redis
              topologyKey: kubernetes.io/hostname
      containers:
      - name: redis
        image: redis:v6.0.8
        command:
          - redis-server
        args:
          - "/etc/redis/redis.conf"
          - "--protected-mode"
          - "no"
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
            - name: redis
              containerPort: 6379
              protocol: TCP
            - name: cluster
              containerPort: 16379
              protocol: TCP
        volumeMounts:
          - name: redis-conf
            mountPath: /etc/redis
      volumes:
      - name: redis-conf
        configMap:
          name: redis-conf
          items:
            - key: redis.conf
              path: redis.conf

---

apiVersion: v1
kind: Service
metadata:
  name: redis-access-service-b
  namespace: redis-cluster-ns
  labels:
    app: redis-access-service-b
spec:
  type: ClusterIP
  ports:
  - name: tcp-port
    protocol: TCP
    port: 6379
    targetPort: 6379
  selector:
    app: redis-stateful-set-b
    appCluster: redis-cluster-b


---
---
apiVersion: v1
kind: Pod
metadata:
  name: python-redis-trib-27slim
  namespace: redis-cluster-ns
  labels:
    name: python-redis-trib-27slim
spec:
  containers:
  - name: python-redis-trib-27slim
    image: python_redis-trib:2.7-slim
    command: ["sh", "-c", "tail -f /dev/null"]

